SEGUNDA LISTA DE EXERCICIOS - INTRODUCAO A INTELIGENCIA ARTIFICIAL

In [190]:
import numpy as np

EXERCICIO 1 - Crie um array contendo os números de 0 a 20.

In [191]:
arr1 = np.arange(1,21)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


EXERCICIO 2 - Crie um array contendo apenas números pares entre 0 e 50.

In [192]:
arr2 = np.arange(0,51,2)
print(arr2)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]


EXERCICIO 3 - Crie um vetor de 100 zeros.

In [193]:
arr3 = np.zeros(100)
print(arr3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


EXERCICIO 4 - Crie uma matriz 4 × 4 de uns.

In [194]:
arr4 = np.ones((4,4))
print(arr4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


EXERCICIO 5 - Crie um vetor de 50 números entre 0 e 1 usando linspace.

In [195]:
arr5 = np.linspace(0,1,50)
print(arr5)

[0.   0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16 0.18 0.2  0.22 0.24 0.27
 0.29 0.31 0.33 0.35 0.37 0.39 0.41 0.43 0.45 0.47 0.49 0.51 0.53 0.55
 0.57 0.59 0.61 0.63 0.65 0.67 0.69 0.71 0.73 0.76 0.78 0.8  0.82 0.84
 0.86 0.88 0.9  0.92 0.94 0.96 0.98 1.  ]


EXERCICIO 6 - Gere 100 numeros aleatorios

In [196]:
arr6 = np.random.random(100)
print(arr6)

[0.65 0.61 0.74 0.53 0.4  0.98 0.19 0.37 0.   0.79 0.25 0.96 0.03 0.45
 0.7  0.32 0.58 0.58 0.8  0.63 0.13 0.3  0.93 0.24 0.17 0.41 0.08 0.26
 0.25 0.21 0.75 0.37 0.51 0.34 0.82 0.47 0.56 0.13 0.64 0.54 0.86 0.98
 0.25 0.65 0.6  0.56 0.78 0.13 0.46 0.66 0.94 0.72 0.59 0.88 0.65 0.93
 0.52 0.07 0.53 0.29 0.88 0.17 0.87 0.03 0.7  0.16 0.01 0.03 0.72 0.02
 0.76 0.13 0.71 0.36 0.7  0.82 0.26 0.82 0.89 0.88 0.25 0.84 0.7  0.71
 0.75 0.77 0.45 0.67 0.44 0.57 0.61 0.07 0.71 0.82 0.6  0.97 0.97 0.95
 0.64 0.4 ]


EXERCICIO 7 - Gere 100 números aleatórios de distribuição normal.

In [197]:
arr7 = np.random.standard_normal(100)
print(arr7)

[-0.79  0.28 -1.03  0.06  0.64  0.04  0.73 -0.62  1.2   0.99 -1.39 -0.48
  1.43  0.66  0.04 -1.34 -0.55  0.63 -0.42 -0.9  -1.17 -0.88  0.08 -0.08
 -1.06 -0.29  0.51 -0.11 -1.46 -0.61 -1.09 -1.92 -2.6  -0.34  2.04  0.39
  0.95 -2.04  0.01  1.09 -0.35  1.08 -0.15 -0.12  1.42  0.82 -0.74  2.87
  2.7  -0.72 -1.   -0.48  1.27 -0.63  0.64 -0.46  2.05  1.02 -0.47 -0.06
  0.58  1.44  0.23  1.45 -0.78 -0.44 -0.07 -1.95  0.37 -0.14 -0.19 -1.31
 -0.63  0.85  0.71 -1.93 -0.21  0.91 -0.62  0.25  1.66 -0.51 -1.    1.23
 -0.25  0.49 -1.48  0.94 -1.17 -1.64 -0.53  1.52 -0.54  0.75  0.36 -0.94
 -0.9  -0.09 -1.47 -1.07]


EXERCICIO 8 - Gere 100 números aleatórios de distribuição normal.

In [198]:
arr8 = np.random.random(size=(5,5))
print(arr8)

[[0.87 0.42 0.05 0.03 0.56]
 [0.63 0.21 0.77 0.15 0.92]
 [0.9  0.77 0.09 0.62 0.56]
 [0.91 0.5  0.11 0.08 0.28]
 [0.55 0.69 0.4  0.73 0.27]]


EXERCICIO 9 - Calcule a média de um vetor aleatório.

In [199]:
arr9 = np.random.random(100)
media_arr9 = np.mean(arr9)
print(arr9)
print(f"Media do array 9: {media_arr9}")

[0.98 0.84 0.24 0.61 0.54 0.97 0.18 0.18 0.59 0.12 0.11 0.65 0.06 0.98
 0.59 0.47 0.13 0.8  0.43 0.4  0.23 0.78 0.73 0.81 0.22 0.63 0.55 0.6
 0.35 0.82 0.78 0.29 0.8  0.39 0.1  0.89 0.16 0.3  0.07 0.75 0.63 0.8
 0.19 0.13 0.16 0.47 0.32 0.73 0.6  0.58 0.34 0.13 0.37 0.29 0.51 0.71
 0.62 0.07 0.81 0.51 0.98 0.14 0.37 0.95 0.77 0.69 0.   0.81 0.93 0.08
 0.51 0.51 0.18 0.87 0.09 0.6  0.91 0.76 0.89 0.36 0.05 0.19 0.87 0.52
 0.37 0.53 0.75 0.69 0.43 0.24 0.73 1.   0.91 0.66 0.68 0.69 0.82 0.58
 0.57 0.83]
Media do array 9: 0.5259987336943823


EXERCICIO 10 - Calcule o desvio padrão de um vetor.

In [200]:
arr10 = np.random.random(10)
desvio_arr10 = np.std(arr10)
print(arr10)
print(f"Desvio padrao do arr10: {desvio_arr10}")

[0.93 0.63 0.44 0.82 0.35 0.44 0.27 0.78 0.95 0.25]
Desvio padrao do arr10: 0.2576795250113951


EXERCICIO 11 - Crie dois vetores e calcule a soma.

In [201]:
arr11a = np.array([1,2,3])
arr11b = np.array([4,5,6])
soma11 = arr11a + arr11b
print(f"arr11a: {arr11a}")
print(f"arr11b: {arr11b}")
print(f"arr11a + arr11b = {soma11}")


arr11a: [1 2 3]
arr11b: [4 5 6]
arr11a + arr11b = [5 7 9]


EXERCICIO 12 - Multiplique todos os elementos de um vetor por 10.

In [202]:
arr12 = np.arange(1,11)
print(arr12)
print("Multiplicando arr12 por 10...")
arr12 *= 10
print(arr12)


[ 1  2  3  4  5  6  7  8  9 10]
Multiplicando arr12 por 10...
[ 10  20  30  40  50  60  70  80  90 100]


EXERCICIO 13 - Calcule o seno de um vetor.

In [203]:
arr13 = np.array([10,20,30])
sen_arr13 = np.sin(arr13)
print(f"arr13: {arr13}")
print(f"Seno de arr13: {sen_arr13}")

arr13: [10 20 30]
Seno de arr13: [-0.54  0.91 -0.99]


EXERCICIO 14 - Calcule o logaritmo de um vetor.

In [204]:
arr14 = np.array([5,6,7])
log_arr14 = np.log(arr14)
print(f"arr14: {arr14}")
print(f"Ln de arr14: {log_arr14}")

arr14: [5 6 7]
Ln de arr14: [1.61 1.79 1.95]


EXERCICIO 15 - Crie uma matriz 3 × 3 e calcule sua transposta.

In [205]:
arr15 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr15)
arr15_t = np.transpose(arr15)
print(arr15_t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


EXERCICIO 16 - Calcule o determinante de uma matriz.

In [206]:
arr16 = np.identity(3)
det_arr16 = np.linalg.det(arr16)
print(arr16)
print(f"Determinante de arr16: {det_arr16}")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determinante de arr16: 1.0


EXERCICIO 17 - Multiplique duas matrizes 3 × 3.

In [207]:
arr17a = np.identity(3)
arr17b = arr15.copy()
resultado17 = np.linalg.matmul(arr17a,arr17b)
print(arr17a)
print(arr17b)
print(resultado17)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


EXERCICIO 18 - Gere uma matriz 100 × 100 e calcule sua média.

In [208]:
arr18 = np.identity(100)
media_arr18 = np.mean(arr18)
print(media_arr18)

0.01


EXERCICIO 19 - Gere uma matriz e encontre o maior valor.

In [209]:
arr19 = np.array([[1,1,1],[2,2,2],[3,3,3]])
max_arr19 = np.max(arr19)
print(arr19)
print(f"Max de arr19: {max_arr19}")

[[1 1 1]
 [2 2 2]
 [3 3 3]]
Max de arr19: 3


EXERCICIO 20 - Encontre o menor valor de um array.

In [210]:
arr20 = np.array([[4,4,4],[5,5,5],[6,6,6]])
min_arr20 = np.min(arr20)
print(arr20)
print(f"Min de arr20: {min_arr20}")

[[4 4 4]
 [5 5 5]
 [6 6 6]]
Min de arr20: 4


EXERCICIO 21 - Ordene um vetor.

In [211]:
arr21 = np.array([2,3,1,2,3,2,2,1,3,5,7])
arr21_ordenado = np.sort(arr21)
print(f"arr21: {arr21}")
print(f"arr21 ordenado: {arr21_ordenado}")

arr21: [2 3 1 2 3 2 2 1 3 5 7]
arr21 ordenado: [1 1 2 2 2 2 3 3 3 5 7]


EXERCICIO 22 - Inverta um vetor.

In [212]:
arr22 = np.array([8,4,2,5,6,8,6,5,4,3,2,2])
arr22_invertido = np.invert(arr22)
print("Invertendo sinal:")
print(f"arr22: {arr22}")
print(f"arr22 invertido: {arr22_invertido}\n")
print("Invertendo ordem dos elementos:")
arr22_invertido = arr22[::-1]
print(f"Arr22 invertido: {arr22_invertido}")

Invertendo sinal:
arr22: [8 4 2 5 6 8 6 5 4 3 2 2]
arr22 invertido: [-9 -5 -3 -6 -7 -9 -7 -6 -5 -4 -3 -3]

Invertendo ordem dos elementos:
Arr22 invertido: [2 2 3 4 5 6 8 6 5 2 4 8]


EXERCICIO 23 - Selecione os elementos maiores que 0.5 de um vetor aleatório.

In [213]:
arr23 = np.random.random(10)
print(f"farr23: {arr23}")
print(f"Valores maiores que 0.5 no arr32: {arr23[arr23 > 0.5]}")

farr23: [0.55 0.77 0.96 0.35 0.05 0.55 0.1  0.21 0.18 0.44]
Valores maiores que 0.5 no arr32: [0.55 0.77 0.96 0.55]


EXERCICIO 24 - Substitua todos os valores negativos por zero.

In [214]:
arr24 = np.arange(-10,11)
arr24[arr24 < 0] = 0
print(arr24)

[ 0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  5  6  7  8  9 10]


EXERCICIO 25 - Crie um vetor e normalize seus valores entre 0 e 1.

In [215]:
arr25 = np.arange(1,11)
print(f"arr25: {arr25}")
norma_arr25 = np.linalg.norm(arr25)
arr25_normalizado = arr25/norma_arr25
print(f"arr25 normalizado: {arr25_normalizado}")

arr25: [ 1  2  3  4  5  6  7  8  9 10]
arr25 normalizado: [0.05 0.1  0.15 0.2  0.25 0.31 0.36 0.41 0.46 0.51]


EXERCICIO 26 - Gere um vetor de retornos financeiros e calcule média.

In [216]:
retornos = np.random.normal(0.1,0.5,1000)
media = np.mean(retornos)
risco = np.std(retornos)
print(media)
print(risco)

0.11457923677321127
0.5006620384425645


EXERCICIO 27 - Simule 1000 preços usando passeio aleatório.

In [238]:
#desativando notação cíentifica
np.set_printoptions(suppress=True, precision=2)

preco_inicial = 100
dias_simulados = 1000

media = 0.01
variacao = 0.001

retornos = np.random.normal(media, variacao, dias_simulados)

historico_precos = preco_inicial * np.cumprod(1 + retornos)
print(historico_precos)


[    100.9      101.9      102.9      104.03     104.98     105.97
     107.04     107.9      109.1      110.24     111.39     112.48
     113.43     114.44     115.61     116.76     117.87     119.03
     120.1      121.18     122.22     123.31     124.39     125.72
     127.22     128.4      129.57     130.97     132.13     133.54
     135.22     136.57     138.19     139.58     141.15     142.68
     144.08     145.39     147.03     148.36     149.84     151.23
     152.88     154.29     155.49     156.94     158.64     160.34
     161.74     163.41     164.88     166.73     168.26     169.9
     171.42     173.28     174.99     176.95     178.78     180.37
     182.22     184.27     186.47     188.08     190.34     192.07
     194.       195.83     197.89     199.99     201.65     203.65
     206.08     208.16     209.94     211.82     214.18     216.22
     218.51     220.7      223.02     225.25     227.41     229.92
     232.22     234.64     236.74     239.08     241.6      244

EXERCICIO 28 - Calcule a matriz identidade 5 × 5.

In [218]:
arr28 = np.identity(5)
print(arr28)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


EXERCICIO 29 - Calcule a matriz identidade 5 × 5.

In [219]:
arr29a = np.array([[1,2],[3,4]])
arr29b = np.array([[5,6],[7,8]])
print(arr29a)
print(arr29b)
print(arr29a * arr29b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]


EXERCICIO 30 - Calcule a inversa de uma matriz.

In [220]:
arr30 = np.array([[1,2],[3,4]])
arr30_invertido = np.linalg.inv(arr30)
print(arr30)
print(arr30_invertido)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


EXERCICIO 31 - Crie uma matriz diagonal.

In [221]:
arr31 = np.diag([1,2,3])
print(arr31)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


EXERCICIO 32 - Extraia a diagonal de uma matriz.

In [222]:
arr32 = np.identity(3)
diag_arr32 = np.diagonal(arr32)
print(arr32)
print(diag_arr32)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]


EXERCICIO 33 - Calcule a soma por linhas de uma matriz. 

In [223]:
arr33 = np.array([[1,2,3],[4,5,6]])
soma_linhas_arr33 = np.sum(arr33,axis=1)
print(arr33)
print(soma_linhas_arr33)

[[1 2 3]
 [4 5 6]]
[ 6 15]


EXERCICIO 34 - Calcule a soma por colunas de uma matriz.

In [224]:
arr34 = arr33.copy()
soma_colunas_arr34 = np.sum(arr34,axis=0)
print(arr34)
print(soma_colunas_arr34)

[[1 2 3]
 [4 5 6]]
[5 7 9]


EXERCICIO 35 - Gere uma matriz 1000 × 1000 e calcule o tempo de multiplicação matricial.

In [225]:
import time

arr35a = np.zeros(shape=(1000,1000))
arr35b = np.ones(shape=(1000,1000))

inicio = time.perf_counter()

mult = np.multiply(arr35a,arr35b)

fim = time.perf_counter()

tempo_execucao = fim - inicio

print(f"Multiplicacao realizada em {tempo_execucao} segundos")

Multiplicacao realizada em 0.00498275899917644 segundos


EXERCICIO 36 - Compare loop Python vs NumPy.

In [226]:
import time

inicio1 = time.perf_counter()

x = 0
n = 100_000_000
t = 10_000_000
for c in range(n):
    x += c

fim1 = time.perf_counter()
tempo_for = fim1 - inicio1
print(f"Tempo do for loop: {tempo_for} segundos")

inicio2 = time.perf_counter()

x = 0
#Separando os dados em blocos para minimizar o consumo de memória RAM
for i in range(0,n,t):
    x += np.sum(np.arange(i,i+t, dtype=np.int64))

fim2 = time.perf_counter()
tempo_np = fim2 - inicio2
print(f"Tempo do loop numpy: {tempo_np} segundos")

Tempo do for loop: 5.387059591001162 segundos
Tempo do loop numpy: 0.13418201199965551 segundos



EXERCICIO 37 - Simule 10000 retornos financeiros e calcule o retorno acumulativo da sequência

In [227]:
retornos = np.random.normal(0.01,0.05,1000)

valor_inicial = 1
valor_final = valor_inicial * np.prod(1 + retornos)

print(valor_final)

retorno_acumulado = valor_inicial * np.cumprod(1 + retornos)
print(retorno_acumulado)


61247.39747282454
[    0.96     0.96     0.97     0.95     0.97     0.95     0.84     0.85
     0.89     0.92     0.92     0.95     1.02     1.01     1.05     1.14
     1.15     1.28     1.42     1.49     1.52     1.62     1.61     1.67
     1.84     1.89     1.88     1.87     2.12     2.07     2.24     2.45
     2.61     2.67     2.69     2.8      2.79     2.84     2.95     2.93
     2.92     2.94     2.94     3.11     3.16     3.22     3.17     3.15
     3.27     3.19     3.       3.03     3.22     3.81     3.96     3.88
     3.88     3.84     4.31     4.41     4.42     4.37     4.24     4.
     4.32     4.07     3.99     4.12     4.27     4.14     4.04     4.03
     4.13     4.15     4.33     4.33     4.34     4.77     4.65     4.82
     4.93     4.81     4.89     4.78     5.19     5.62     5.89     5.89
     5.6      5.9      6.11     6.47     7.06     7.67     7.97     7.88
     8.31     8.83     9.64    10.18    11.      11.22    11.34    12.
    12.48    12.41    12.51    13.24 