SEGUNDA LISTA DE EXERCICIOS - INTRODUCAO A INTELIGENCIA ARTIFICIAL

In [118]:
import numpy as np

EXERCICIO 1 - Crie um array contendo os números de 0 a 20.

In [119]:
arr1 = np.arange(1,21)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


EXERCICIO 2 - Crie um array contendo apenas números pares entre 0 e 50.

In [120]:
arr2 = np.arange(0,51,2)
print(arr2)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]


EXERCICIO 3 - Crie um vetor de 100 zeros.

In [121]:
arr3 = np.zeros(100)
print(arr3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


EXERCICIO 4 - Crie uma matriz 4 × 4 de uns.

In [122]:
arr4 = np.ones((4,4))
print(arr4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


EXERCICIO 5 - Crie um vetor de 50 números entre 0 e 1 usando linspace.

In [123]:
arr5 = np.linspace(0,1,50)
print(arr5)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


EXERCICIO 6 - Gere 100 numeros aleatorios

In [124]:
arr6 = np.random.random(100)
print(arr6)

[0.87153177 0.52860098 0.26936702 0.20116929 0.98068514 0.61920992
 0.32053843 0.19614945 0.69393287 0.36852324 0.87459271 0.91990521
 0.91534078 0.02005909 0.77119153 0.1371699  0.48112938 0.76520557
 0.79617757 0.77127597 0.79751773 0.91696093 0.71752445 0.52539071
 0.48564777 0.65247984 0.6528033  0.69037625 0.22118075 0.29690201
 0.3024639  0.74650087 0.69168871 0.99638502 0.72645915 0.32362942
 0.03066464 0.38648878 0.8603177  0.85006986 0.33348067 0.60141342
 0.76211687 0.23558103 0.34358667 0.11593512 0.42519416 0.18248379
 0.34146983 0.21548682 0.34860172 0.53546303 0.02314015 0.4591849
 0.11163564 0.37677358 0.20483789 0.48619465 0.78473438 0.46082073
 0.20370885 0.24742018 0.11583282 0.16432304 0.00936902 0.23639374
 0.41584144 0.37225016 0.08883543 0.0863728  0.73925854 0.12107779
 0.60686535 0.66650411 0.02259762 0.08983492 0.57902839 0.53064796
 0.81848273 0.21444069 0.54200681 0.32333436 0.90543446 0.34832455
 0.1133999  0.74724012 0.22144565 0.98288722 0.87466404 0.17127

EXERCICIO 7 - Gere 100 números aleatórios de distribuição normal.

In [125]:
arr7 = np.random.standard_normal(100)
print(arr7)

[-1.39024465 -0.80177283  0.29500791  0.11714721 -0.4632978   0.51415365
  1.12917262 -0.61408445 -1.29634399 -0.58502657 -0.95903408  0.23414302
 -0.45293622 -2.62589404 -0.04774973 -1.60291755 -0.17957184 -0.91985681
  0.88977302 -0.72037038 -0.63060597 -0.77803289 -0.43491198 -1.72600347
 -0.32994805 -1.0043874  -0.67191821  2.13877804 -0.97830194  0.37809331
 -0.6969519   0.3825337  -0.04157103 -0.44995295  0.47577257 -1.15880429
 -0.0734646   1.52960308  0.34992112 -0.88042626 -0.37879875 -0.32102246
 -0.50425941 -0.89314901  0.77167473 -1.71695308 -0.53392062  1.26806634
 -1.04547006 -1.26772613  0.94925831  0.66622179  0.6002789  -1.87965915
 -0.55329001  0.35060588  0.45200173  1.27805831  0.00863173 -0.67912611
 -0.17712107 -1.02743465  0.77143267  0.68756527 -1.15224213  0.86720835
 -0.40266006  0.75713181 -0.92783634  0.94041766  0.40226871  0.35089668
  2.83828669  0.94035262 -0.62027993 -0.52851996 -0.15562381  0.48918433
 -1.55449852  0.70708614  0.17607724  0.25166508  0

EXERCICIO 8 - Gere 100 números aleatórios de distribuição normal.

In [126]:
arr8 = np.random.random(size=(5,5))
print(arr8)

[[0.77923103 0.41233667 0.90325558 0.53143723 0.16880256]
 [0.59898031 0.41779849 0.42663694 0.55020314 0.02215541]
 [0.5019457  0.26105214 0.76250438 0.16670245 0.20798855]
 [0.34981069 0.30459914 0.23948561 0.24675444 0.07783351]
 [0.28693753 0.71509304 0.65368012 0.5727283  0.58374717]]


EXERCICIO 9 - Calcule a média de um vetor aleatório.

In [127]:
arr9 = np.random.random(100)
media_arr9 = np.mean(arr9)
print(arr9)
print(f"Media do array 9: {media_arr9}")

[0.2853861  0.6878101  0.47836782 0.94026143 0.07748023 0.75943746
 0.42433342 0.46293698 0.09500999 0.54371479 0.76431575 0.80553775
 0.85678023 0.56797192 0.69875732 0.23636434 0.3734904  0.71777771
 0.13809809 0.42456953 0.00729149 0.70382199 0.68529639 0.66481043
 0.9387496  0.37774519 0.73399439 0.52614221 0.78634844 0.61300046
 0.33796241 0.31610487 0.40673232 0.56320347 0.5910019  0.62960769
 0.50774086 0.42938947 0.55633928 0.01285461 0.26468225 0.45774878
 0.07151012 0.30813792 0.49382266 0.11253492 0.58146676 0.00885755
 0.59980749 0.83319672 0.51998118 0.20239019 0.18848118 0.8680312
 0.91731604 0.78220023 0.73580831 0.30980242 0.50994082 0.73380643
 0.11716114 0.28105331 0.89110534 0.57200823 0.89226591 0.13236851
 0.14340882 0.12358143 0.7803888  0.78446279 0.2531223  0.83239468
 0.13284854 0.32895598 0.75006827 0.98616083 0.85028833 0.82371952
 0.75225062 0.32957023 0.860226   0.0482712  0.80260235 0.7973469
 0.31455386 0.28829497 0.56585223 0.44656297 0.00507032 0.106463

EXERCICIO 10 - Calcule o desvio padrão de um vetor.

In [128]:
arr10 = np.random.random(10)
desvio_arr10 = np.std(arr10)
print(arr10)
print(f"Desvio padrao do arr10: {desvio_arr10}")

[0.66147801 0.7457868  0.20631045 0.95307873 0.82858845 0.14125983
 0.33288898 0.01896536 0.44756548 0.72658647]
Desvio padrao do arr10: 0.30458259393936077


EXERCICIO 11 - Crie dois vetores e calcule a soma.

In [129]:
arr11a = np.array([1,2,3])
arr11b = np.array([4,5,6])
soma11 = arr11a + arr11b
print(f"arr11a: {arr11a}")
print(f"arr11b: {arr11b}")
print(f"arr11a + arr11b = {soma11}")


arr11a: [1 2 3]
arr11b: [4 5 6]
arr11a + arr11b = [5 7 9]


EXERCICIO 12 - Multiplique todos os elementos de um vetor por 10.

In [130]:
arr12 = np.arange(1,11)
print(arr12)
print("Multiplicando arr12 por 10...")
arr12 *= 10
print(arr12)


[ 1  2  3  4  5  6  7  8  9 10]
Multiplicando arr12 por 10...
[ 10  20  30  40  50  60  70  80  90 100]


EXERCICIO 13 - Calcule o seno de um vetor.

In [131]:
arr13 = np.array([10,20,30])
sen_arr13 = np.sin(arr13)
print(f"arr13: {arr13}")
print(f"Seno de arr13: {sen_arr13}")

arr13: [10 20 30]
Seno de arr13: [-0.54402111  0.91294525 -0.98803162]


EXERCICIO 14 - Calcule o logaritmo de um vetor.

In [132]:
arr14 = np.array([5,6,7])
log_arr14 = np.log(arr14)
print(f"arr14: {arr14}")
print(f"Ln de arr14: {log_arr14}")

arr14: [5 6 7]
Ln de arr14: [1.60943791 1.79175947 1.94591015]


EXERCICIO 15 - Crie uma matriz 3 × 3 e calcule sua transposta.

In [133]:
arr15 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr15)
arr15_t = np.transpose(arr15)
print(arr15_t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


EXERCICIO 16 - Calcule o determinante de uma matriz.

In [134]:
arr16 = np.identity(3)
det_arr16 = np.linalg.det(arr16)
print(arr16)
print(f"Determinante de arr16: {det_arr16}")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determinante de arr16: 1.0


EXERCICIO 17 - Multiplique duas matrizes 3 × 3.

In [135]:
arr17a = np.identity(3)
arr17b = arr15.copy()
resultado17 = np.linalg.matmul(arr17a,arr17b)
print(arr17a)
print(arr17b)
print(resultado17)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


EXERCICIO 18 - Gere uma matriz 100 × 100 e calcule sua média.

In [136]:
arr18 = np.identity(100)
media_arr18 = np.mean(arr18)
print(media_arr18)

0.01


EXERCICIO 19 - Gere uma matriz e encontre o maior valor.

In [137]:
arr19 = np.array([[1,1,1],[2,2,2],[3,3,3]])
max_arr19 = np.max(arr19)
print(arr19)
print(f"Max de arr19: {max_arr19}")

[[1 1 1]
 [2 2 2]
 [3 3 3]]
Max de arr19: 3


EXERCICIO 20 - Encontre o menor valor de um array.

In [138]:
arr20 = np.array([[4,4,4],[5,5,5],[6,6,6]])
min_arr20 = np.min(arr20)
print(arr20)
print(f"Min de arr20: {min_arr20}")

[[4 4 4]
 [5 5 5]
 [6 6 6]]
Min de arr20: 4


EXERCICIO 21 - Ordene um vetor.

In [139]:
arr21 = np.array([2,3,1,2,3,2,2,1,3,5,7])
arr21_ordenado = np.sort(arr21)
print(f"arr21: {arr21}")
print(f"arr21 ordenado: {arr21_ordenado}")

arr21: [2 3 1 2 3 2 2 1 3 5 7]
arr21 ordenado: [1 1 2 2 2 2 3 3 3 5 7]


EXERCICIO 22 - Inverta um vetor.

In [140]:
arr22 = np.array([8,4,2,5,6,8,6,5,4,3,2,2])
arr22_invertido = np.invert(arr22)
print("Invertendo sinal:")
print(f"arr22: {arr22}")
print(f"arr22 invertido: {arr22_invertido}\n")
print("Invertendo ordem dos elementos:")
arr22_invertido = arr22[::-1]
print(f"Arr22 invertido: {arr22_invertido}")

Invertendo sinal:
arr22: [8 4 2 5 6 8 6 5 4 3 2 2]
arr22 invertido: [-9 -5 -3 -6 -7 -9 -7 -6 -5 -4 -3 -3]

Invertendo ordem dos elementos:
Arr22 invertido: [2 2 3 4 5 6 8 6 5 2 4 8]


EXERCICIO 23 - Selecione os elementos maiores que 0.5 de um vetor aleatório.

In [141]:
arr23 = np.random.random(10)
print(f"farr23: {arr23}")
print(f"Valores maiores que 0.5 no arr32: {arr23[arr23 > 0.5]}")

farr23: [0.59532264 0.75356198 0.21289293 0.76585461 0.7568439  0.43892045
 0.01177425 0.62254256 0.85464112 0.25304378]
Valores maiores que 0.5 no arr32: [0.59532264 0.75356198 0.76585461 0.7568439  0.62254256 0.85464112]


EXERCICIO 24 - Substitua todos os valores negativos por zero.

In [142]:
arr24 = np.arange(-10,11)
arr24[arr24 < 0] = 0
print(arr24)

[ 0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  5  6  7  8  9 10]


EXERCICIO 25 - Crie um vetor e normalize seus valores entre 0 e 1.

In [143]:
arr25 = np.arange(1,11)
print(f"arr25: {arr25}")
norma_arr25 = np.linalg.norm(arr25)
arr25_normalizado = arr25/norma_arr25
print(f"arr25 normalizado: {arr25_normalizado}")

arr25: [ 1  2  3  4  5  6  7  8  9 10]
arr25 normalizado: [0.05096472 0.10192944 0.15289416 0.20385888 0.2548236  0.30578831
 0.35675303 0.40771775 0.45868247 0.50964719]


EXERCICIO 26 - Gere um vetor de retornos financeiros e calcule média.

In [144]:
retornos = np.random.normal(0.1,0.5,1000)
media = np.mean(retornos)
risco = np.std(retornos)
print(media)
print(risco)

0.10280989127232151
0.5330233364725039


EXERCICIO 27 - Simule 1000 preços usando passeio aleatório.

EXERCICIO 28 - Calcule a matriz identidade 5 × 5.

In [145]:
arr28 = np.identity(5)
print(arr28)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


EXERCICIO 29 - Calcule a matriz identidade 5 × 5.

In [146]:
arr29a = np.array([[1,2],[3,4]])
arr29b = np.array([[5,6],[7,8]])
print(arr29a)
print(arr29b)
print(arr29a * arr29b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]


EXERCICIO 30 - Calcule a inversa de uma matriz.

In [147]:
arr30 = np.array([[1,2],[3,4]])
arr30_invertido = np.linalg.inv(arr30)
print(arr30)
print(arr30_invertido)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


EXERCICIO 31 - Crie uma matriz diagonal.

In [148]:
arr31 = np.diag([1,2,3])
print(arr31)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


EXERCICIO 32 - Extraia a diagonal de uma matriz.

In [149]:
arr32 = np.identity(3)
diag_arr32 = np.diagonal(arr32)
print(arr32)
print(diag_arr32)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]


EXERCICIO 33 - Calcule a soma por linhas de uma matriz. 

In [150]:
arr33 = np.array([[1,2,3],[4,5,6]])
soma_linhas_arr33 = np.sum(arr33,axis=1)
print(arr33)
print(soma_linhas_arr33)

[[1 2 3]
 [4 5 6]]
[ 6 15]


EXERCICIO 34 - Calcule a soma por colunas de uma matriz.

In [151]:
arr34 = arr33.copy()
soma_colunas_arr34 = np.sum(arr34,axis=0)
print(arr34)
print(soma_colunas_arr34)

[[1 2 3]
 [4 5 6]]
[5 7 9]


EXERCICIO 35 - Gere uma matriz 1000 × 1000 e calcule o tempo de multiplicação matricial.

In [152]:
import time

arr35a = np.zeros(shape=(1000,1000))
arr35b = np.ones(shape=(1000,1000))

inicio = time.perf_counter()

mult = np.multiply(arr35a,arr35b)

fim = time.perf_counter()

tempo_execucao = fim - inicio

print(f"Multiplicacao realizada em {tempo_execucao} segundos")

Multiplicacao realizada em 0.004146637998928782 segundos


EXERCICIO 36 - Compare loop Python vs NumPy.

EXERCICIO 37 - Simule 10000 retornos financeiros e calcule o retorno acumulativo da sequência